# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'opening.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1900, 1000)
        MainWindow.setMinimumSize(QtCore.QSize(1900, 1000))
        MainWindow.setMaximumSize(QtCore.QSize(2050, 1900))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("background:url(boki_back.png)")
        self.widget.setObjectName("widget")
        self.logo = QtWidgets.QLabel(self)
        self.logo.setGeometry(QtCore.QRect(100, 130, 1061, 481))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("boki_logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.frame = QtWidgets.QFrame(self)
        self.frame.setGeometry(QtCore.QRect(1410, 680, 391, 251))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.start_btn = QtWidgets.QPushButton(self.frame)
        self.start_btn.setMinimumSize(QtCore.QSize(250, 70))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.start_btn.setFont(font)
        self.start_btn.setStyleSheet("border-radius:7px;\n"
"background:rgb(76, 82, 120);\n"
"border: 3px solid rgb(229, 204, 111);\n"
"color: rgb(229, 204, 111);\n"
"")
        self.start_btn.setObjectName("start_btn")
        self.verticalLayout_2.addWidget(self.start_btn)
        self.end_btn = QtWidgets.QPushButton(self.frame)
        self.end_btn.setMinimumSize(QtCore.QSize(250, 70))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.end_btn.setFont(font)
        self.end_btn.setStyleSheet("border-radius:7px;\n"
"background:rgb(76, 82, 120);\n"
"border: 3px solid rgb(229, 204, 111);\n"
"color: rgb(229, 204, 111);")
        self.end_btn.setObjectName("end_btn")
        self.verticalLayout_2.addWidget(self.end_btn)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">시작</p></body></html>"))
        self.start_btn.setText(_translate("MainWindow", "Game Start"))
        self.end_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:400; font-style:normal;\">종료</span></p></body></html>"))
        self.end_btn.setText(_translate("MainWindow", "Game End"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
